// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fp

// ExpBySqrtPp1o4 is equivalent to z.Exp(x, 3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66).
// It raises x to the (p+1)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPp1o4(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_110    = 2*_11
	//	_111    = 1 + _110
	//	_111000 = _111 << 3
	//	_111111 = _111 + _111000
	//	x12     = _111111 << 6 + _111111
	//	x24     = x12 << 12 + x12
	//	x48     = x24 << 24 + x24
	//	i59     = x48 << 6
	//	x96     = i59 << 42 + x48
	//	x192    = x96 << 96 + x96
	//	x246    = x192 << 54 + i59 + _111111
	//	return    2*((x246 << 3 + _11) << 4 + _11)
	//
	// Operations: 253 squares 12 multiplies
	var t0, t1, t2, t3 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: t0 = x^0x6
	t0.Square(z)

	// Step 4: t0 = x^0x7
	t0.Mul(&x, &t0)

	// Step 7: t1 = x^0x38
	t1.Square(&t0)
	for s := 1; s < 3; s++ {
		t1.Square(&t1)
	}

	// Step 8: t0 = x^0x3f
	t0.Mul(&t0, &t1)

	// Step 14: t1 = x^0xfc0
	t1.Square(&t0)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 15: t1 = x^0xfff
	t1.Mul(&t0, &t1)

	// Step 27: t2 = x^0xfff000
	t2.Square(&t1)
	for s := 1; s < 12; s++ {
		t2.Square(&t2)
	}

	// Step 28: t1 = x^0xffffff
	t1.Mul(&t1, &t2)

	// Step 52: t2 = x^0xffffff000000
	t2.Square(&t1)
	for s := 1; s < 24; s++ {
		t2.Square(&t2)
	}

	// Step 53: t2 = x^0xffffffffffff
	t2.Mul(&t1, &t2)

	// Step 59: t1 = x^0x3fffffffffffc0
	t1.Square(&t2)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 101: t3 = x^0xffffffffffff000000000000
	t3.Square(&t1)
	for s := 1; s < 42; s++ {
		t3.Square(&t3)
	}

	// Step 102: t2 = x^0xffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 198: t3 = x^0xffffffffffffffffffffffff000000000000000000000000
	t3.Square(&t2)
	for s := 1; s < 96; s++ {
		t3.Square(&t3)
	}

	// Step 199: t2 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 253: t2 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffc0000000000000
	for range 54 {
		t2.Square(&t2)
	}

	// Step 254: t1 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc0
	t1.Mul(&t1, &t2)

	// Step 255: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 258: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8
	for range 3 {
		t0.Square(&t0)
	}

	// Step 259: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
	t0.Mul(z, &t0)

	// Step 263: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb0
	for range 4 {
		t0.Square(&t0)
	}

	// Step 264: z = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb3
	z.Mul(z, &t0)

	// Step 265: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff66
	z.Square(z)

	return z
}

// ExpBySqrtPm3o4 is equivalent to z.Exp(x, 3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff65).
// It raises x to the (p-3)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPm3o4(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_110    = 2*_11
	//	_111    = 1 + _110
	//	_111000 = _111 << 3
	//	_111111 = _111 + _111000
	//	x12     = _111111 << 6 + _111111
	//	x24     = x12 << 12 + x12
	//	x48     = x24 << 24 + x24
	//	i59     = x48 << 6
	//	x96     = i59 << 42 + x48
	//	x192    = x96 << 96 + x96
	//	x246    = x192 << 54 + i59 + _111111
	//	i265    = ((x246 << 3 + _11) << 3 + 1) << 2
	//	return    1 + i265
	//
	// Operations: 253 squares 13 multiplies
	var t0, t1, t2, t3 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: t0 = x^0x6
	t0.Square(z)

	// Step 4: t0 = x^0x7
	t0.Mul(&x, &t0)

	// Step 7: t1 = x^0x38
	t1.Square(&t0)
	for s := 1; s < 3; s++ {
		t1.Square(&t1)
	}

	// Step 8: t0 = x^0x3f
	t0.Mul(&t0, &t1)

	// Step 14: t1 = x^0xfc0
	t1.Square(&t0)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 15: t1 = x^0xfff
	t1.Mul(&t0, &t1)

	// Step 27: t2 = x^0xfff000
	t2.Square(&t1)
	for s := 1; s < 12; s++ {
		t2.Square(&t2)
	}

	// Step 28: t1 = x^0xffffff
	t1.Mul(&t1, &t2)

	// Step 52: t2 = x^0xffffff000000
	t2.Square(&t1)
	for s := 1; s < 24; s++ {
		t2.Square(&t2)
	}

	// Step 53: t2 = x^0xffffffffffff
	t2.Mul(&t1, &t2)

	// Step 59: t1 = x^0x3fffffffffffc0
	t1.Square(&t2)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 101: t3 = x^0xffffffffffff000000000000
	t3.Square(&t1)
	for s := 1; s < 42; s++ {
		t3.Square(&t3)
	}

	// Step 102: t2 = x^0xffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 198: t3 = x^0xffffffffffffffffffffffff000000000000000000000000
	t3.Square(&t2)
	for s := 1; s < 96; s++ {
		t3.Square(&t3)
	}

	// Step 199: t2 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 253: t2 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffc0000000000000
	for range 54 {
		t2.Square(&t2)
	}

	// Step 254: t1 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc0
	t1.Mul(&t1, &t2)

	// Step 255: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 258: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8
	for range 3 {
		t0.Square(&t0)
	}

	// Step 259: z = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
	z.Mul(z, &t0)

	// Step 262: z = x^0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd8
	for range 3 {
		z.Square(z)
	}

	// Step 263: z = x^0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd9
	z.Mul(&x, z)

	// Step 265: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff64
	for range 2 {
		z.Square(z)
	}

	// Step 266: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff65
	z.Mul(&x, z)

	return z
}

// ExpByLegendreExp is equivalent to z.Exp(x, 7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffecb).
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByLegendreExp(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_110    = 2*_11
	//	_111    = 1 + _110
	//	_111000 = _111 << 3
	//	_111111 = _111 + _111000
	//	x12     = _111111 << 6 + _111111
	//	x24     = x12 << 12 + x12
	//	x48     = x24 << 24 + x24
	//	i59     = x48 << 6
	//	x96     = i59 << 42 + x48
	//	x192    = x96 << 96 + x96
	//	x246    = x192 << 54 + i59 + _111111
	//	i266    = ((x246 << 3 + _11) << 3 + 1) << 3
	//	return    _11 + i266
	//
	// Operations: 254 squares 13 multiplies
	var t0, t1, t2, t3 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: t0 = x^0x6
	t0.Square(z)

	// Step 4: t0 = x^0x7
	t0.Mul(&x, &t0)

	// Step 7: t1 = x^0x38
	t1.Square(&t0)
	for s := 1; s < 3; s++ {
		t1.Square(&t1)
	}

	// Step 8: t0 = x^0x3f
	t0.Mul(&t0, &t1)

	// Step 14: t1 = x^0xfc0
	t1.Square(&t0)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 15: t1 = x^0xfff
	t1.Mul(&t0, &t1)

	// Step 27: t2 = x^0xfff000
	t2.Square(&t1)
	for s := 1; s < 12; s++ {
		t2.Square(&t2)
	}

	// Step 28: t1 = x^0xffffff
	t1.Mul(&t1, &t2)

	// Step 52: t2 = x^0xffffff000000
	t2.Square(&t1)
	for s := 1; s < 24; s++ {
		t2.Square(&t2)
	}

	// Step 53: t2 = x^0xffffffffffff
	t2.Mul(&t1, &t2)

	// Step 59: t1 = x^0x3fffffffffffc0
	t1.Square(&t2)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 101: t3 = x^0xffffffffffff000000000000
	t3.Square(&t1)
	for s := 1; s < 42; s++ {
		t3.Square(&t3)
	}

	// Step 102: t2 = x^0xffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 198: t3 = x^0xffffffffffffffffffffffff000000000000000000000000
	t3.Square(&t2)
	for s := 1; s < 96; s++ {
		t3.Square(&t3)
	}

	// Step 199: t2 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t2.Mul(&t2, &t3)

	// Step 253: t2 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffc0000000000000
	for range 54 {
		t2.Square(&t2)
	}

	// Step 254: t1 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc0
	t1.Mul(&t1, &t2)

	// Step 255: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 258: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8
	for range 3 {
		t0.Square(&t0)
	}

	// Step 259: t0 = x^0x1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb
	t0.Mul(z, &t0)

	// Step 262: t0 = x^0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd8
	for range 3 {
		t0.Square(&t0)
	}

	// Step 263: t0 = x^0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd9
	t0.Mul(&x, &t0)

	// Step 266: t0 = x^0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffec8
	for range 3 {
		t0.Square(&t0)
	}

	// Step 267: z = x^0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffecb
	z.Mul(z, &t0)

	return z
}

// ExpByCbrt2q1o3 is equivalent to z.Exp(x, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa90f).
// It raises x to the (2q-1)/3 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrt2q1o3(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_110      = 2*_11
	//	_111      = 1 + _110
	//	_1000     = 1 + _111
	//	_1000000  = _1000 << 3
	//	_1000010  = _10 + _1000000
	//	_10000100 = 2*_1000010
	//	_10001011 = _111 + _10000100
	//	_11001101 = _1000010 + _10001011
	//	i13       = 2*_11001101
	//	i14       = 1 + i13
	//	i16       = _10000100 + i14 + i14
	//	i27       = (i13 + i16) << 10
	//	i28       = i16 + i27
	//	i39       = i27 << 10 + i28
	//	i40       = i14 + i39
	//	i138      = ((i40 << 32 + i40) << 32 + i40) << 32
	//	i205      = ((i40 + i138) << 32 + i40) << 32 + i40
	//	return      (i205 << 32 + i40) << 33 + i40 + i39
	//
	// Operations: 252 squares 21 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t0 = x^0x3
	t0.Mul(&x, z)

	// Step 3: t0 = x^0x6
	t0.Square(&t0)

	// Step 4: t1 = x^0x7
	t1.Mul(&x, &t0)

	// Step 5: t0 = x^0x8
	t0.Mul(&x, &t1)

	// Step 8: t0 = x^0x40
	for range 3 {
		t0.Square(&t0)
	}

	// Step 9: t0 = x^0x42
	t0.Mul(z, &t0)

	// Step 10: z = x^0x84
	z.Square(&t0)

	// Step 11: t1 = x^0x8b
	t1.Mul(&t1, z)

	// Step 12: t0 = x^0xcd
	t0.Mul(&t0, &t1)

	// Step 13: t1 = x^0x19a
	t1.Square(&t0)

	// Step 14: t0 = x^0x19b
	t0.Mul(&x, &t1)

	// Step 15: z = x^0x21f
	z.Mul(z, &t0)

	// Step 16: z = x^0x3ba
	z.Mul(&t0, z)

	// Step 17: t1 = x^0x554
	t1.Mul(&t1, z)

	// Step 27: t1 = x^0x155000
	for range 10 {
		t1.Square(&t1)
	}

	// Step 28: z = x^0x1553ba
	z.Mul(z, &t1)

	// Step 38: t1 = x^0x55400000
	for range 10 {
		t1.Square(&t1)
	}

	// Step 39: z = x^0x555553ba
	z.Mul(z, &t1)

	// Step 40: t0 = x^0x55555555
	t0.Mul(&t0, z)

	// Step 72: t1 = x^0x5555555500000000
	t1.Square(&t0)
	for s := 1; s < 32; s++ {
		t1.Square(&t1)
	}

	// Step 73: t1 = x^0x5555555555555555
	t1.Mul(&t0, &t1)

	// Step 105: t1 = x^0x555555555555555500000000
	for range 32 {
		t1.Square(&t1)
	}

	// Step 106: t1 = x^0x555555555555555555555555
	t1.Mul(&t0, &t1)

	// Step 138: t1 = x^0x55555555555555555555555500000000
	for range 32 {
		t1.Square(&t1)
	}

	// Step 139: t1 = x^0x55555555555555555555555555555555
	t1.Mul(&t0, &t1)

	// Step 171: t1 = x^0x5555555555555555555555555555555500000000
	for range 32 {
		t1.Square(&t1)
	}

	// Step 172: t1 = x^0x5555555555555555555555555555555555555555
	t1.Mul(&t0, &t1)

	// Step 204: t1 = x^0x555555555555555555555555555555555555555500000000
	for range 32 {
		t1.Square(&t1)
	}

	// Step 205: t1 = x^0x555555555555555555555555555555555555555555555555
	t1.Mul(&t0, &t1)

	// Step 237: t1 = x^0x55555555555555555555555555555555555555555555555500000000
	for range 32 {
		t1.Square(&t1)
	}

	// Step 238: t1 = x^0x55555555555555555555555555555555555555555555555555555555
	t1.Mul(&t0, &t1)

	// Step 271: t1 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa00000000
	for range 33 {
		t1.Square(&t1)
	}

	// Step 272: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa55555555
	t0.Mul(&t0, &t1)

	// Step 273: z = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa90f
	z.Mul(z, &t0)

	return z
}
