// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fp

// ExpBySqrtPp1o4 is equivalent to z.Exp(x, 3fffffffffffffffffffffffffffffffffffffffffffffffffffffffc0000000000000000000000000000000000000000000000000000000).
// It raises x to the (p+1)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPp1o4(x Element) *Element {
	// addition chain:
	//
	//	_10       = 2*1
	//	_11       = 1 + _10
	//	_1100     = _11 << 2
	//	_1111     = _11 + _1100
	//	_11110000 = _1111 << 4
	//	_11111111 = _1111 + _11110000
	//	x16       = _11111111 << 8 + _11111111
	//	x32       = x16 << 16 + x16
	//	x64       = x32 << 32 + x32
	//	x128      = x64 << 64 + x64
	//	x192      = x128 << 64 + x64
	//	x224      = x192 << 32 + x32
	//	return      x224 << 222
	//
	// Operations: 445 squares 9 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 4: t0 = x^0xc
	t0.Square(z)
	for s := 1; s < 2; s++ {
		t0.Square(&t0)
	}

	// Step 5: z = x^0xf
	z.Mul(z, &t0)

	// Step 9: t0 = x^0xf0
	t0.Square(z)
	for s := 1; s < 4; s++ {
		t0.Square(&t0)
	}

	// Step 10: z = x^0xff
	z.Mul(z, &t0)

	// Step 18: t0 = x^0xff00
	t0.Square(z)
	for s := 1; s < 8; s++ {
		t0.Square(&t0)
	}

	// Step 19: z = x^0xffff
	z.Mul(z, &t0)

	// Step 35: t0 = x^0xffff0000
	t0.Square(z)
	for s := 1; s < 16; s++ {
		t0.Square(&t0)
	}

	// Step 36: z = x^0xffffffff
	z.Mul(z, &t0)

	// Step 68: t0 = x^0xffffffff00000000
	t0.Square(z)
	for s := 1; s < 32; s++ {
		t0.Square(&t0)
	}

	// Step 69: t0 = x^0xffffffffffffffff
	t0.Mul(z, &t0)

	// Step 133: t1 = x^0xffffffffffffffff0000000000000000
	t1.Square(&t0)
	for s := 1; s < 64; s++ {
		t1.Square(&t1)
	}

	// Step 134: t1 = x^0xffffffffffffffffffffffffffffffff
	t1.Mul(&t0, &t1)

	// Step 198: t1 = x^0xffffffffffffffffffffffffffffffff0000000000000000
	for range 64 {
		t1.Square(&t1)
	}

	// Step 199: t0 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 231: t0 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 232: z = x^0xffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	// Step 454: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffc0000000000000000000000000000000000000000000000000000000
	for range 222 {
		z.Square(z)
	}

	return z
}

// ExpBySqrtPm3o4 is equivalent to z.Exp(x, 3fffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffff).
// It raises x to the (p-3)/4 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPm3o4(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_110    = 2*_11
	//	_111    = 1 + _110
	//	_111000 = _111 << 3
	//	_111111 = _111 + _111000
	//	x12     = _111111 << 6 + _111111
	//	x24     = x12 << 12 + x12
	//	i34     = x24 << 6
	//	x30     = _111111 + i34
	//	x48     = i34 << 18 + x24
	//	x96     = x48 << 48 + x48
	//	x192    = x96 << 96 + x96
	//	x222    = x192 << 30 + x30
	//	x223    = 2*x222 + 1
	//	return    x223 << 223 + x222
	//
	// Operations: 445 squares 12 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: z = x^0x6
	z.Square(z)

	// Step 4: z = x^0x7
	z.Mul(&x, z)

	// Step 7: t0 = x^0x38
	t0.Square(z)
	for s := 1; s < 3; s++ {
		t0.Square(&t0)
	}

	// Step 8: z = x^0x3f
	z.Mul(z, &t0)

	// Step 14: t0 = x^0xfc0
	t0.Square(z)
	for s := 1; s < 6; s++ {
		t0.Square(&t0)
	}

	// Step 15: t0 = x^0xfff
	t0.Mul(z, &t0)

	// Step 27: t1 = x^0xfff000
	t1.Square(&t0)
	for s := 1; s < 12; s++ {
		t1.Square(&t1)
	}

	// Step 28: t0 = x^0xffffff
	t0.Mul(&t0, &t1)

	// Step 34: t1 = x^0x3fffffc0
	t1.Square(&t0)
	for s := 1; s < 6; s++ {
		t1.Square(&t1)
	}

	// Step 35: z = x^0x3fffffff
	z.Mul(z, &t1)

	// Step 53: t1 = x^0xffffff000000
	for range 18 {
		t1.Square(&t1)
	}

	// Step 54: t0 = x^0xffffffffffff
	t0.Mul(&t0, &t1)

	// Step 102: t1 = x^0xffffffffffff000000000000
	t1.Square(&t0)
	for s := 1; s < 48; s++ {
		t1.Square(&t1)
	}

	// Step 103: t0 = x^0xffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 199: t1 = x^0xffffffffffffffffffffffff000000000000000000000000
	t1.Square(&t0)
	for s := 1; s < 96; s++ {
		t1.Square(&t1)
	}

	// Step 200: t0 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 230: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffc0000000
	for range 30 {
		t0.Square(&t0)
	}

	// Step 231: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	// Step 232: t0 = x^0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffe
	t0.Square(z)

	// Step 233: t0 = x^0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&x, &t0)

	// Step 456: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffff80000000000000000000000000000000000000000000000000000000
	for range 223 {
		t0.Square(&t0)
	}

	// Step 457: z = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	return z
}

// ExpByLegendreExp is equivalent to z.Exp(x, 7fffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffff).
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByLegendreExp(x Element) *Element {
	// addition chain:
	//
	//	_10      = 2*1
	//	_11      = 1 + _10
	//	_110     = 2*_11
	//	_111     = 1 + _110
	//	_111000  = _111 << 3
	//	_111111  = _111 + _111000
	//	_1111110 = 2*_111111
	//	_1111111 = 1 + _1111110
	//	x12      = _1111110 << 5 + _111111
	//	x24      = x12 << 12 + x12
	//	i36      = x24 << 7
	//	x31      = _1111111 + i36
	//	x48      = i36 << 17 + x24
	//	x96      = x48 << 48 + x48
	//	x192     = x96 << 96 + x96
	//	x223     = x192 << 31 + x31
	//	return     x223 << 224 + x223
	//
	// Operations: 446 squares 12 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: z = x^0x6
	z.Square(z)

	// Step 4: z = x^0x7
	z.Mul(&x, z)

	// Step 7: t0 = x^0x38
	t0.Square(z)
	for s := 1; s < 3; s++ {
		t0.Square(&t0)
	}

	// Step 8: t0 = x^0x3f
	t0.Mul(z, &t0)

	// Step 9: t1 = x^0x7e
	t1.Square(&t0)

	// Step 10: z = x^0x7f
	z.Mul(&x, &t1)

	// Step 15: t1 = x^0xfc0
	for range 5 {
		t1.Square(&t1)
	}

	// Step 16: t0 = x^0xfff
	t0.Mul(&t0, &t1)

	// Step 28: t1 = x^0xfff000
	t1.Square(&t0)
	for s := 1; s < 12; s++ {
		t1.Square(&t1)
	}

	// Step 29: t0 = x^0xffffff
	t0.Mul(&t0, &t1)

	// Step 36: t1 = x^0x7fffff80
	t1.Square(&t0)
	for s := 1; s < 7; s++ {
		t1.Square(&t1)
	}

	// Step 37: z = x^0x7fffffff
	z.Mul(z, &t1)

	// Step 54: t1 = x^0xffffff000000
	for range 17 {
		t1.Square(&t1)
	}

	// Step 55: t0 = x^0xffffffffffff
	t0.Mul(&t0, &t1)

	// Step 103: t1 = x^0xffffffffffff000000000000
	t1.Square(&t0)
	for s := 1; s < 48; s++ {
		t1.Square(&t1)
	}

	// Step 104: t0 = x^0xffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 200: t1 = x^0xffffffffffffffffffffffff000000000000000000000000
	t1.Square(&t0)
	for s := 1; s < 96; s++ {
		t1.Square(&t1)
	}

	// Step 201: t0 = x^0xffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 232: t0 = x^0x7fffffffffffffffffffffffffffffffffffffffffffffff80000000
	for range 31 {
		t0.Square(&t0)
	}

	// Step 233: z = x^0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	// Step 457: t0 = x^0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000
	t0.Square(z)
	for s := 1; s < 224; s++ {
		t0.Square(&t0)
	}

	// Step 458: z = x^0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	return z
}

// ExpByCbrt2q1o3 is equivalent to z.Exp(x, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff).
// It raises x to the (2q-1)/3 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrt2q1o3(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_100    = 2*_10
	//	_110    = _10 + _100
	//	_1100   = 2*_110
	//	_10010  = _110 + _1100
	//	_100100 = 2*_10010
	//	_101010 = _110 + _100100
	//	i10     = _101010 << 3
	//	i18     = i10 << 6 + i10 + _10
	//	i37     = (2*i18 + _110) << 15 + i18 + 1
	//	i38     = _10 + i37
	//	i39     = 1 + i38
	//	i40     = i37 + i39
	//	x32     = i39 + i40
	//	i106    = ((i38 + x32) << 30 + i38) << 32 + i38
	//	i204    = ((i106 << 32 + i38) << 32 + i38) << 32
	//	i272    = ((i38 + i204) << 33 + i40) << 32 + x32
	//	i370    = ((i272 << 32 + x32) << 32 + x32) << 32
	//	i437    = ((x32 + i370) << 32 + x32) << 32 + x32
	//	return    i437 << 32 + x32
	//
	// Operations: 444 squares 26 multiplies
	var t0, t1, t2 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: t0 = x^0x4
	t0.Square(z)

	// Step 3: t1 = x^0x6
	t1.Mul(z, &t0)

	// Step 4: t0 = x^0xc
	t0.Square(&t1)

	// Step 5: t0 = x^0x12
	t0.Mul(&t1, &t0)

	// Step 6: t0 = x^0x24
	t0.Square(&t0)

	// Step 7: t0 = x^0x2a
	t0.Mul(&t1, &t0)

	// Step 10: t0 = x^0x150
	for range 3 {
		t0.Square(&t0)
	}

	// Step 16: t2 = x^0x5400
	t2.Square(&t0)
	for s := 1; s < 6; s++ {
		t2.Square(&t2)
	}

	// Step 17: t0 = x^0x5550
	t0.Mul(&t0, &t2)

	// Step 18: t0 = x^0x5552
	t0.Mul(z, &t0)

	// Step 19: t2 = x^0xaaa4
	t2.Square(&t0)

	// Step 20: t1 = x^0xaaaa
	t1.Mul(&t1, &t2)

	// Step 35: t1 = x^0x55550000
	for range 15 {
		t1.Square(&t1)
	}

	// Step 36: t0 = x^0x55555552
	t0.Mul(&t0, &t1)

	// Step 37: t0 = x^0x55555553
	t0.Mul(&x, &t0)

	// Step 38: t1 = x^0x55555555
	t1.Mul(z, &t0)

	// Step 39: z = x^0x55555556
	z.Mul(&x, &t1)

	// Step 40: t0 = x^0xaaaaaaa9
	t0.Mul(&t0, z)

	// Step 41: z = x^0xffffffff
	z.Mul(z, &t0)

	// Step 42: t2 = x^0x155555554
	t2.Mul(&t1, z)

	// Step 72: t2 = x^0x5555555500000000
	for range 30 {
		t2.Square(&t2)
	}

	// Step 73: t2 = x^0x5555555555555555
	t2.Mul(&t1, &t2)

	// Step 105: t2 = x^0x555555555555555500000000
	for range 32 {
		t2.Square(&t2)
	}

	// Step 106: t2 = x^0x555555555555555555555555
	t2.Mul(&t1, &t2)

	// Step 138: t2 = x^0x55555555555555555555555500000000
	for range 32 {
		t2.Square(&t2)
	}

	// Step 139: t2 = x^0x55555555555555555555555555555555
	t2.Mul(&t1, &t2)

	// Step 171: t2 = x^0x5555555555555555555555555555555500000000
	for range 32 {
		t2.Square(&t2)
	}

	// Step 172: t2 = x^0x5555555555555555555555555555555555555555
	t2.Mul(&t1, &t2)

	// Step 204: t2 = x^0x555555555555555555555555555555555555555500000000
	for range 32 {
		t2.Square(&t2)
	}

	// Step 205: t1 = x^0x555555555555555555555555555555555555555555555555
	t1.Mul(&t1, &t2)

	// Step 238: t1 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa00000000
	for range 33 {
		t1.Square(&t1)
	}

	// Step 239: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9
	t0.Mul(&t0, &t1)

	// Step 271: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa900000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 272: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffff
	t0.Mul(z, &t0)

	// Step 304: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 305: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffff
	t0.Mul(z, &t0)

	// Step 337: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 338: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffff
	t0.Mul(z, &t0)

	// Step 370: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 371: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffff
	t0.Mul(z, &t0)

	// Step 403: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 404: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffff
	t0.Mul(z, &t0)

	// Step 436: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 437: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(z, &t0)

	// Step 469: t0 = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffffffffffff00000000
	for range 32 {
		t0.Square(&t0)
	}

	// Step 470: z = x^0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	return z
}
