package gc256a

import (
	"math/big"
	"math/bits"

	fp "github.com/yelhousni/divide-and-pair/gc256a/fp"
)

// PointAffine point on a twisted Edwards curve in affine coordinates
type PointAffine struct {
	X, Y fp.Element
}

// PointProj point in projective coordinates (X:Y:Z) with x=X/Z, y=Y/Z
type PointProj struct {
	X, Y, Z fp.Element
}

// Set sets p to p1 and returns p
func (p *PointAffine) Set(p1 *PointAffine) *PointAffine {
	p.X.Set(&p1.X)
	p.Y.Set(&p1.Y)
	return p
}

// Equal returns true if p and p1 are equal
func (p *PointAffine) Equal(p1 *PointAffine) bool {
	return p.X.Equal(&p1.X) && p.Y.Equal(&p1.Y)
}

// IsZero returns true if p is the identity (0, 1)
func (p *PointAffine) IsZero() bool {
	return p.X.IsZero() && p.Y.IsOne()
}

// IsOnCurve checks if the point is on the curve: Ax^2 + y^2 = 1 + Dx^2*y^2
func (p *PointAffine) IsOnCurve() bool {
	initOnce.Do(initCurveParams)

	var lhs, rhs, tmp fp.Element

	tmp.Mul(&p.Y, &p.Y)
	lhs.Mul(&p.X, &p.X)
	mulByA(&lhs)
	lhs.Add(&lhs, &tmp) // A*x^2 + y^2

	tmp.Mul(&p.X, &p.X).
		Mul(&tmp, &p.Y).
		Mul(&tmp, &p.Y).
		Mul(&tmp, &curveParams.D)
	rhs.SetOne().Add(&rhs, &tmp) // 1 + D*x^2*y^2

	return lhs.Equal(&rhs)
}

// Neg negates a point
func (p *PointAffine) Neg(p1 *PointAffine) *PointAffine {
	p.X.Neg(&p1.X)
	p.Y.Set(&p1.Y)
	return p
}

// Add adds two affine points using the unified addition formula for twisted Edwards curves
func (p *PointAffine) Add(p1, p2 *PointAffine) *PointAffine {
	initOnce.Do(initCurveParams)

	var x1y2, y1x2, y1y2, x1x2, dxy fp.Element

	x1y2.Mul(&p1.X, &p2.Y)
	y1x2.Mul(&p1.Y, &p2.X)
	y1y2.Mul(&p1.Y, &p2.Y)
	x1x2.Mul(&p1.X, &p2.X)
	dxy.Mul(&curveParams.D, &x1x2).Mul(&dxy, &y1y2)

	var numX, numY, denX, denY fp.Element
	numX.Add(&x1y2, &y1x2)
	ax1x2 := x1x2
	mulByA(&ax1x2)
	numY.Sub(&y1y2, &ax1x2)

	denX.SetOne().Add(&denX, &dxy)
	denY.SetOne().Sub(&denY, &dxy)

	denX.Inverse(&denX)
	denY.Inverse(&denY)

	p.X.Mul(&numX, &denX)
	p.Y.Mul(&numY, &denY)
	return p
}

// Double doubles a point
func (p *PointAffine) Double(p1 *PointAffine) *PointAffine {
	return p.Add(p1, p1)
}

// ScalarMultiplication scalar multiplication of a point
func (p *PointAffine) ScalarMultiplication(p1 *PointAffine, scalar *big.Int) *PointAffine {
	var proj, res PointProj
	proj.FromAffine(p1)
	res.ScalarMultiplication(&proj, scalar)
	res.ToAffine(p)
	return p
}

// --- Projective coordinates ---

// Set sets p to p1
func (p *PointProj) Set(p1 *PointProj) *PointProj {
	p.X.Set(&p1.X)
	p.Y.Set(&p1.Y)
	p.Z.Set(&p1.Z)
	return p
}

// FromAffine converts affine to projective
func (p *PointProj) FromAffine(a *PointAffine) *PointProj {
	p.X.Set(&a.X)
	p.Y.Set(&a.Y)
	p.Z.SetOne()
	return p
}

// ToAffine converts projective to affine
func (p *PointProj) ToAffine(a *PointAffine) *PointAffine {
	var zInv fp.Element
	zInv.Inverse(&p.Z)
	a.X.Mul(&p.X, &zInv)
	a.Y.Mul(&p.Y, &zInv)
	return a
}

// IsZero returns true if p is the identity (0:1:1)
func (p *PointProj) IsZero() bool {
	return p.X.IsZero() && p.Y.Equal(&p.Z)
}

func (p *PointProj) setInfinity() *PointProj {
	p.X.SetZero()
	p.Y.SetOne()
	p.Z.SetOne()
	return p
}

func (p *PointProj) Neg(p1 *PointProj) *PointProj {
	p.X.Neg(&p1.X)
	p.Y.Set(&p1.Y)
	p.Z.Set(&p1.Z)
	return p
}

func (p *PointProj) Add(p1, p2 *PointProj) *PointProj {
	initOnce.Do(initCurveParams)
	var A, B, C, D, E, F, G, H, I fp.Element
	A.Mul(&p1.Z, &p2.Z)
	B.Square(&A)
	C.Mul(&p1.X, &p2.X)
	D.Mul(&p1.Y, &p2.Y)
	E.Mul(&curveParams.D, &C)
	E.Mul(&E, &D)
	F.Sub(&B, &E)
	G.Add(&B, &E)
	H.Add(&p1.X, &p1.Y)
	I.Add(&p2.X, &p2.Y)
	p.X.Mul(&H, &I).Sub(&p.X, &C).Sub(&p.X, &D).Mul(&p.X, &A).Mul(&p.X, &F)
	var aC fp.Element
	aC.Set(&C)
	mulByA(&aC)
	p.Y.Sub(&D, &aC).Mul(&p.Y, &A).Mul(&p.Y, &G)
	p.Z.Mul(&F, &G)
	return p
}

func (p *PointProj) Double(p1 *PointProj) *PointProj {
	var B, C, D, E, F, H, J fp.Element
	B.Add(&p1.X, &p1.Y).Square(&B)
	C.Square(&p1.X)
	D.Square(&p1.Y)
	E.Set(&C)
	mulByA(&E)
	F.Add(&E, &D)
	H.Square(&p1.Z)
	J.Sub(&F, &H).Sub(&J, &H)
	p.X.Sub(&B, &C).Sub(&p.X, &D).Mul(&p.X, &J)
	p.Y.Sub(&E, &D).Mul(&p.Y, &F)
	p.Z.Mul(&F, &J)
	return p
}

func (p *PointProj) ScalarMultiplication(p1 *PointProj, scalar *big.Int) *PointProj {
	var _scalar big.Int
	_scalar.Set(scalar)
	p.Set(p1)
	if _scalar.Sign() == -1 {
		_scalar.Neg(&_scalar)
		p.Neg(p)
	}
	var res PointProj
	res.setInfinity()
	const wordSize = bits.UintSize
	sWords := _scalar.Bits()
	for i := len(sWords) - 1; i >= 0; i-- {
		ithWord := sWords[i]
		for k := 0; k < wordSize; k++ {
			res.Double(&res)
			kthBit := (ithWord >> (wordSize - 1 - k)) & 1
			if kthBit == 1 {
				res.Add(&res, p)
			}
		}
	}
	p.Set(&res)
	return p
}

// ClearCofactor sets p to [h]p, where h is the curve cofactor, mapping p
// into the prime-order subgroup, and returns p. It uses a fixed short
// addition chain (see mulByCofactor).
func (p *PointAffine) ClearCofactor() *PointAffine {
	var proj PointProj
	proj.FromAffine(p)
	proj.mulByCofactor(&proj)
	proj.ToAffine(p)
	return p
}

// Code generated by internal/generator BEGIN mulByOrder. DO NOT EDIT.

// mulByOrder computes p = [ℓ]a and returns p, where
//
//	ℓ = 28948022309329048855892746252171976963338560298092253442512153408785530358887
//
// is the 255-bit prime subgroup order. The scalar multiplication is unrolled
// as a short addition chain generated with github.com/mmcloughlin/addchain v0.4.0.
//
// The unified Add/Double formulas are valid for arbitrary curve points
// (including the identity and points outside the ℓ-torsion subgroup), so the
// result is the identity if and only if a is in the prime-order subgroup.
//
// Addition chain:
//
//	_10       = 2*1
//	_100      = 2*_10
//	_110      = _10 + _100
//	_111      = 1 + _110
//	_1000     = 1 + _111
//	_10000    = 2*_1000
//	_10111    = _111 + _10000
//	_11011    = _100 + _10111
//	_100000   = 2*_10000
//	_100011   = _1000 + _11011
//	_100100   = 1 + _100011
//	_111111   = _11011 + _100100
//	_1000000  = 1 + _111111
//	_1000101  = _110 + _111111
//	_1010000  = _10000 + _1000000
//	_1010101  = _10000 + _1000101
//	_1011011  = _110 + _1010101
//	_1100011  = _1000 + _1011011
//	_10000111 = _100100 + _1100011
//	_11010111 = _1010000 + _10000111
//	_11011101 = _110 + _11010111
//	i160      = ((_100011 + _11011101) << 130 + _11011101 + _100000) << 6
//	i179      = ((_100011 + i160) << 10 + _11011101) << 6 + _111111
//	i207      = ((i179 << 10 + _10000111) << 7 + _1011011) << 9
//	i228      = ((_1100011 + i207) << 6 + _10111) << 12 + _1000101
//	i254      = ((i228 << 9 + _11010111) << 7 + _1010101) << 8
//	i278      = ((_1011011 + i254) << 9 + _11011) << 12 + _1100011
//	return      i278 << 5 + _111
//
// Operations: 250 point doublings, 34 point additions.
func (p *PointProj) mulByOrder(a *PointProj) *PointProj {
	// x is a working copy of the input so that p may alias a.
	var x, z PointProj
	var t0, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10, t11, t12 PointProj
	x.Set(a)

	// Step 1: z = [0x2]a
	z.Double(&x)
	// Step 2: t1 = [0x4]a
	t1.Double(&z)
	// Step 3: t9 = [0x6]a
	t9.Add(&z, &t1)
	// Step 4: z = [0x7]a
	z.Add(&x, &t9)
	// Step 5: t0 = [0x8]a
	t0.Add(&x, &z)
	// Step 6: t2 = [0x10]a
	t2.Double(&t0)
	// Step 7: t6 = [0x17]a
	t6.Add(&z, &t2)
	// Step 8: t1 = [0x1b]a
	t1.Add(&t1, &t6)
	// Step 9: t11 = [0x20]a
	t11.Double(&t2)
	// Step 10: t10 = [0x23]a
	t10.Add(&t0, &t1)
	// Step 11: t7 = [0x24]a
	t7.Add(&x, &t10)
	// Step 12: t8 = [0x3f]a
	t8.Add(&t1, &t7)
	// Step 13: t3 = [0x40]a
	t3.Add(&x, &t8)
	// Step 14: t5 = [0x45]a
	t5.Add(&t9, &t8)
	// Step 15: t4 = [0x50]a
	t4.Add(&t2, &t3)
	// Step 16: t3 = [0x55]a
	t3.Add(&t2, &t5)
	// Step 17: t2 = [0x5b]a
	t2.Add(&t9, &t3)
	// Step 18: t0 = [0x63]a
	t0.Add(&t0, &t2)
	// Step 19: t7 = [0x87]a
	t7.Add(&t7, &t0)
	// Step 20: t4 = [0xd7]a
	t4.Add(&t4, &t7)
	// Step 21: t9 = [0xdd]a
	t9.Add(&t9, &t4)
	// Step 22: t12 = [0x100]a
	t12.Add(&t10, &t9)
	// Step 23: t12 = [0x40000000000000000000000000000000000]a
	for range 130 {
		t12.Double(&t12)
	}
	// Step 24: t12 = [0x400000000000000000000000000000000dd]a
	t12.Add(&t9, &t12)
	// Step 25: t11 = [0x400000000000000000000000000000000fd]a
	t11.Add(&t11, &t12)
	// Step 26: t11 = [0x1000000000000000000000000000000003f40]a
	for range 6 {
		t11.Double(&t11)
	}
	// Step 27: t10 = [0x1000000000000000000000000000000003f63]a
	t10.Add(&t10, &t11)
	// Step 28: t10 = [0x400000000000000000000000000000000fd8c00]a
	for range 10 {
		t10.Double(&t10)
	}
	// Step 29: t9 = [0x400000000000000000000000000000000fd8cdd]a
	t9.Add(&t9, &t10)
	// Step 30: t9 = [0x1000000000000000000000000000000003f633740]a
	for range 6 {
		t9.Double(&t9)
	}
	// Step 31: t8 = [0x1000000000000000000000000000000003f63377f]a
	t8.Add(&t8, &t9)
	// Step 32: t8 = [0x400000000000000000000000000000000fd8cddfc00]a
	for range 10 {
		t8.Double(&t8)
	}
	// Step 33: t7 = [0x400000000000000000000000000000000fd8cddfc87]a
	t7.Add(&t7, &t8)
	// Step 34: t7 = [0x2000000000000000000000000000000007ec66efe4380]a
	for range 7 {
		t7.Double(&t7)
	}
	// Step 35: t7 = [0x2000000000000000000000000000000007ec66efe43db]a
	t7.Add(&t2, &t7)
	// Step 36: t7 = [0x400000000000000000000000000000000fd8cddfc87b600]a
	for range 9 {
		t7.Double(&t7)
	}
	// Step 37: t7 = [0x400000000000000000000000000000000fd8cddfc87b663]a
	t7.Add(&t0, &t7)
	// Step 38: t7 = [0x1000000000000000000000000000000003f63377f21ed98c0]a
	for range 6 {
		t7.Double(&t7)
	}
	// Step 39: t6 = [0x1000000000000000000000000000000003f63377f21ed98d7]a
	t6.Add(&t6, &t7)
	// Step 40: t6 = [0x1000000000000000000000000000000003f63377f21ed98d7000]a
	for range 12 {
		t6.Double(&t6)
	}
	// Step 41: t5 = [0x1000000000000000000000000000000003f63377f21ed98d7045]a
	t5.Add(&t5, &t6)
	// Step 42: t5 = [0x2000000000000000000000000000000007ec66efe43db31ae08a00]a
	for range 9 {
		t5.Double(&t5)
	}
	// Step 43: t4 = [0x2000000000000000000000000000000007ec66efe43db31ae08ad7]a
	t4.Add(&t4, &t5)
	// Step 44: t4 = [0x1000000000000000000000000000000003f63377f21ed98d70456b80]a
	for range 7 {
		t4.Double(&t4)
	}
	// Step 45: t3 = [0x1000000000000000000000000000000003f63377f21ed98d70456bd5]a
	t3.Add(&t3, &t4)
	// Step 46: t3 = [0x1000000000000000000000000000000003f63377f21ed98d70456bd500]a
	for range 8 {
		t3.Double(&t3)
	}
	// Step 47: t2 = [0x1000000000000000000000000000000003f63377f21ed98d70456bd55b]a
	t2.Add(&t2, &t3)
	// Step 48: t2 = [0x2000000000000000000000000000000007ec66efe43db31ae08ad7aab600]a
	for range 9 {
		t2.Double(&t2)
	}
	// Step 49: t1 = [0x2000000000000000000000000000000007ec66efe43db31ae08ad7aab61b]a
	t1.Add(&t1, &t2)
	// Step 50: t1 = [0x2000000000000000000000000000000007ec66efe43db31ae08ad7aab61b000]a
	for range 12 {
		t1.Double(&t1)
	}
	// Step 51: t0 = [0x2000000000000000000000000000000007ec66efe43db31ae08ad7aab61b063]a
	t0.Add(&t0, &t1)
	// Step 52: t0 = [0x400000000000000000000000000000000fd8cddfc87b6635c115af556c360c60]a
	for range 5 {
		t0.Double(&t0)
	}
	// Step 53: z = [0x400000000000000000000000000000000fd8cddfc87b6635c115af556c360c67]a
	z.Add(&z, &t0)

	return p.Set(&z)
}

// Code generated by internal/generator END mulByOrder. DO NOT EDIT.

// Code generated by internal/generator BEGIN mulByCofactor. DO NOT EDIT.

// mulByCofactor computes p = [h]a and returns p, where
//
//	h = 4
//
// is the cofactor. The result lies in the prime-order subgroup for any
// curve point a. The chain was generated with github.com/mmcloughlin/addchain v0.4.0.
//
// Addition chain:
//
//	return  1 << 2
//
// Operations: 2 point doublings, 0 point additions.
func (p *PointProj) mulByCofactor(a *PointProj) *PointProj {
	// x is a working copy of the input so that p may alias a.
	var x, z PointProj
	x.Set(a)

	// Step 1: z = [0x4]a
	z.Double(&x)
	z.Double(&z)

	return p.Set(&z)
}

// Code generated by internal/generator END mulByCofactor. DO NOT EDIT.
