package fp

// ExpBySepticFp computes z = x^((p-1)/7) in Fp using the same addition chain
// as E2.ExpBySeptic but with Fp squarings and multiplications.
//
// The exponent (p-1)/7 = 0x12492492492492492492492492492492.
//
// Generated by github.com/mmcloughlin/addchain v0.4.0
func (z *Element) ExpBySepticFp(x Element) *Element {
	// _1000  = 1 << 3
	// _1001  = 1 + _1000
	// i11    = _1001 << 6 + _1001
	// i31    = (i11 << 6 + _1001) << 12 + i11
	// i62    = i31 << 30 + i31
	// return   2*((i62 << 6 + _1001) << 60 + i62)

	var _1000, _1001, i11, i31, i62 Element

	_1000.Square(&x)
	_1000.Square(&_1000)
	_1000.Square(&_1000)

	_1001.Mul(&_1000, &x)

	i11.Set(&_1001)
	for range 6 {
		i11.Square(&i11)
	}
	i11.Mul(&i11, &_1001)

	i31.Set(&i11)
	for range 6 {
		i31.Square(&i31)
	}
	i31.Mul(&i31, &_1001)
	for range 12 {
		i31.Square(&i31)
	}
	i31.Mul(&i31, &i11)

	i62.Set(&i31)
	for range 30 {
		i62.Square(&i62)
	}
	i62.Mul(&i62, &i31)

	z.Set(&i62)
	for range 6 {
		z.Square(z)
	}
	z.Mul(z, &_1001)
	for range 60 {
		z.Square(z)
	}
	z.Mul(z, &i62)
	z.Square(z)

	return z
}
