package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/mmcloughlin/addchain/acc/ir"
	"github.com/mmcloughlin/addchain/meta"
)

// methodSpec describes one generated fixed-scalar multiplication method on
// PointProj.
type methodSpec struct {
	// Name is the method name, e.g. "mulByOrder".
	Name string

	// Doc holds the leading doc comment lines (each starting with "//"),
	// emitted before the addition-chain script and operation counts.
	Doc []string
}

// Markers delimiting a generated method inside each curve's point.go. The
// splice below replaces everything between them (inclusive) on regeneration,
// or appends the block at the end of the file if absent.
func beginMarker(name string) string {
	return fmt.Sprintf("// Code generated by internal/generator BEGIN %s. DO NOT EDIT.", name)
}

func endMarker(name string) string {
	return fmt.Sprintf("// Code generated by internal/generator END %s. DO NOT EDIT.", name)
}

// addchainCitation returns the module/version reference of the addchain
// library used to generate the chains, for inclusion in doc comments.
func addchainCitation() string {
	return fmt.Sprintf("%s %s", meta.Meta.Module(), meta.Meta.ReleaseTag())
}

// emitMethod renders one method block for a curve from the allocated
// addition-chain program, delimited by the generation markers. The block is
// import-free and contains no module-specific strings, so the same bytes are
// valid in both the main and the artifact trees.
func emitMethod(spec methodSpec, prog *ir.Program, script string) (string, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", beginMarker(spec.Name))

	for _, line := range spec.Doc {
		fmt.Fprintf(&b, "%s\n", line)
	}
	fmt.Fprintf(&b, "//\n// Addition chain:\n//\n")
	for _, line := range strings.Split(strings.TrimRight(script, "\n"), "\n") {
		fmt.Fprintf(&b, "//\t%s\n", line)
	}
	fmt.Fprintf(&b, "//\n// Operations: %d point doublings, %d point additions.\n",
		prog.Program.Doubles(), prog.Program.Adds())

	fmt.Fprintf(&b, "func (p *PointProj) %s(a *PointProj) *PointProj {\n", spec.Name)
	fmt.Fprintf(&b, "\t// x is a working copy of the input so that p may alias a.\n")
	fmt.Fprintf(&b, "\tvar x, z PointProj\n")
	if len(prog.Temporaries) > 0 {
		fmt.Fprintf(&b, "\tvar %s PointProj\n", strings.Join(prog.Temporaries, ", "))
	}
	fmt.Fprintf(&b, "\tx.Set(a)\n\n")

	for i, inst := range prog.Instructions {
		out := inst.Output.String()
		fmt.Fprintf(&b, "\t// Step %d: %s = [0x%s]a\n", i+1, out, prog.Chain[inst.Output.Index].Text(16))
		switch op := inst.Op.(type) {
		case ir.Add:
			fmt.Fprintf(&b, "\t%s.Add(&%s, &%s)\n", out, op.X, op.Y)
		case ir.Double:
			fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, op.X)
		case ir.Shift:
			s := int(op.S)
			if op.X.String() != out {
				fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, op.X)
				s--
			}
			switch {
			case s == 1:
				fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, out)
			case s > 1:
				fmt.Fprintf(&b, "\tfor range %d {\n\t\t%s.Double(&%s)\n\t}\n", s, out, out)
			}
		default:
			return "", fmt.Errorf("unexpected op type %T", op)
		}
	}

	fmt.Fprintf(&b, "\n\treturn p.Set(&z)\n}\n\n")
	fmt.Fprintf(&b, "%s\n", endMarker(spec.Name))

	return b.String(), nil
}

// splice inserts a generated method block into the point.go source, replacing
// a previously generated block with the same name if its markers are present,
// or appending at the end of the file otherwise. The result is gofmt'ed.
func splice(src []byte, name, block string) ([]byte, error) {
	bm, em := beginMarker(name), endMarker(name)
	s := string(src)
	begin := strings.Index(s, bm)
	end := strings.Index(s, em)
	switch {
	case begin >= 0 && end > begin:
		s = s[:begin] + strings.TrimSuffix(block, "\n") + s[end+len(em):]
	case begin < 0 && end < 0:
		s = strings.TrimRight(s, "\n") + "\n\n" + block
	default:
		return nil, fmt.Errorf("inconsistent generation markers for %s", name)
	}
	return format.Source([]byte(s))
}
