package main

import (
	"bytes"
	"fmt"
	"go/format"
	"math/big"
	"strings"

	"github.com/mmcloughlin/addchain/acc/ir"
	"github.com/mmcloughlin/addchain/meta"
)

// Markers delimiting the generated mulByOrder method inside each curve's
// point.go. The splice below replaces everything between them (inclusive) on
// regeneration, or appends the block at the end of the file if absent.
const (
	beginMarker = "// Code generated by internal/generator BEGIN mulByOrder. DO NOT EDIT."
	endMarker   = "// Code generated by internal/generator END mulByOrder. DO NOT EDIT."
)

// emitMethod renders the mulByOrder method block for one curve from the
// allocated addition-chain program, delimited by the generation markers. The
// block is import-free and contains no module-specific strings, so the same
// bytes are valid in both the main and the artifact trees.
func emitMethod(c curveConfig, n *big.Int, prog *ir.Program, script string) (string, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "%s\n\n", beginMarker)

	fmt.Fprintf(&b, "// mulByOrder computes p = [ℓ]a and returns p, where\n//\n")
	fmt.Fprintf(&b, "//\tℓ = %s\n", c.Order)
	if c.OrderComment != "" {
		fmt.Fprintf(&b, "//\t  = %s\n", c.OrderComment)
	}
	fmt.Fprintf(&b, "//\n// is the %d-bit prime subgroup order. The scalar multiplication is unrolled\n", n.BitLen())
	fmt.Fprintf(&b, "// as a short addition chain generated with %s %s.\n", meta.Meta.Module(), meta.Meta.ReleaseTag())
	fmt.Fprintf(&b, "//\n// The unified Add/Double formulas are valid for arbitrary curve points\n")
	fmt.Fprintf(&b, "// (including the identity and points outside the ℓ-torsion subgroup), so the\n")
	fmt.Fprintf(&b, "// result is the identity if and only if a is in the prime-order subgroup.\n")
	fmt.Fprintf(&b, "//\n// Addition chain:\n//\n")
	for _, line := range strings.Split(strings.TrimRight(script, "\n"), "\n") {
		fmt.Fprintf(&b, "//\t%s\n", line)
	}
	fmt.Fprintf(&b, "//\n// Operations: %d point doublings, %d point additions.\n",
		prog.Program.Doubles(), prog.Program.Adds())

	fmt.Fprintf(&b, "func (p *PointProj) mulByOrder(a *PointProj) *PointProj {\n")
	fmt.Fprintf(&b, "\t// x is a working copy of the input so that p may alias a.\n")
	fmt.Fprintf(&b, "\tvar x, z PointProj\n")
	if len(prog.Temporaries) > 0 {
		fmt.Fprintf(&b, "\tvar %s PointProj\n", strings.Join(prog.Temporaries, ", "))
	}
	fmt.Fprintf(&b, "\tx.Set(a)\n\n")

	for i, inst := range prog.Instructions {
		out := inst.Output.String()
		fmt.Fprintf(&b, "\t// Step %d: %s = [0x%s]a\n", i+1, out, prog.Chain[inst.Output.Index].Text(16))
		switch op := inst.Op.(type) {
		case ir.Add:
			fmt.Fprintf(&b, "\t%s.Add(&%s, &%s)\n", out, op.X, op.Y)
		case ir.Double:
			fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, op.X)
		case ir.Shift:
			s := int(op.S)
			if op.X.String() != out {
				fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, op.X)
				s--
			}
			switch {
			case s == 1:
				fmt.Fprintf(&b, "\t%s.Double(&%s)\n", out, out)
			case s > 1:
				fmt.Fprintf(&b, "\tfor range %d {\n\t\t%s.Double(&%s)\n\t}\n", s, out, out)
			}
		default:
			return "", fmt.Errorf("unexpected op type %T", op)
		}
	}

	fmt.Fprintf(&b, "\n\treturn p.Set(&z)\n}\n\n")
	fmt.Fprintf(&b, "%s\n", endMarker)

	return b.String(), nil
}

// splice inserts the generated method block into the point.go source,
// replacing a previously generated block if the markers are present, or
// appending at the end of the file otherwise. The result is gofmt'ed.
func splice(src []byte, block string) ([]byte, error) {
	s := string(src)
	begin := strings.Index(s, beginMarker)
	end := strings.Index(s, endMarker)
	switch {
	case begin >= 0 && end > begin:
		s = s[:begin] + strings.TrimSuffix(block, "\n") + s[end+len(endMarker):]
	case begin < 0 && end < 0:
		s = strings.TrimRight(s, "\n") + "\n\n" + block
	default:
		return nil, fmt.Errorf("inconsistent generation markers")
	}
	return format.Source([]byte(s))
}
