// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package fp

// ExpBySqrtPm5o8 is equivalent to z.Exp(x, ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd).
// It raises x to the (p-5)/8 power using a shorter addition chain.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpBySqrtPm5o8(x Element) *Element {
	// addition chain:
	//
	//	_10    = 2*1
	//	_11    = 1 + _10
	//	_1100  = _11 << 2
	//	_1111  = _11 + _1100
	//	_11110 = 2*_1111
	//	_11111 = 1 + _11110
	//	x10    = _11111 << 5 + _11111
	//	x15    = x10 << 5 + _11111
	//	x30    = x15 << 15 + x15
	//	x60    = x30 << 30 + x30
	//	x120   = x60 << 60 + x60
	//	x240   = x120 << 120 + x120
	//	x250   = x240 << 10 + x10
	//	return   x250 << 2 + 1
	//
	// Operations: 251 squares 11 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 4: t0 = x^0xc
	t0.Square(z)
	for s := 1; s < 2; s++ {
		t0.Square(&t0)
	}

	// Step 5: z = x^0xf
	z.Mul(z, &t0)

	// Step 6: z = x^0x1e
	z.Square(z)

	// Step 7: t0 = x^0x1f
	t0.Mul(&x, z)

	// Step 12: z = x^0x3e0
	z.Square(&t0)
	for s := 1; s < 5; s++ {
		z.Square(z)
	}

	// Step 13: z = x^0x3ff
	z.Mul(&t0, z)

	// Step 18: t1 = x^0x7fe0
	t1.Square(z)
	for s := 1; s < 5; s++ {
		t1.Square(&t1)
	}

	// Step 19: t0 = x^0x7fff
	t0.Mul(&t0, &t1)

	// Step 34: t1 = x^0x3fff8000
	t1.Square(&t0)
	for s := 1; s < 15; s++ {
		t1.Square(&t1)
	}

	// Step 35: t0 = x^0x3fffffff
	t0.Mul(&t0, &t1)

	// Step 65: t1 = x^0xfffffffc0000000
	t1.Square(&t0)
	for s := 1; s < 30; s++ {
		t1.Square(&t1)
	}

	// Step 66: t0 = x^0xfffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 126: t1 = x^0xfffffffffffffff000000000000000
	t1.Square(&t0)
	for s := 1; s < 60; s++ {
		t1.Square(&t1)
	}

	// Step 127: t0 = x^0xffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 247: t1 = x^0xffffffffffffffffffffffffffffff000000000000000000000000000000
	t1.Square(&t0)
	for s := 1; s < 120; s++ {
		t1.Square(&t1)
	}

	// Step 248: t0 = x^0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	t0.Mul(&t0, &t1)

	// Step 258: t0 = x^0x3fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc00
	for range 10 {
		t0.Square(&t0)
	}

	// Step 259: z = x^0x3ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
	z.Mul(z, &t0)

	// Step 261: z = x^0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffc
	for range 2 {
		z.Square(z)
	}

	// Step 262: z = x^0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffd
	z.Mul(&x, z)

	return z
}

// ExpByCbrtQPlus2Div9 is equivalent to z.Exp(x, e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e37).
// It raises x to the (q+2)/9 power using a shorter addition chain.
// This is used when q ≡ 7 (mod 9) for efficient cube root computation.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrtQPlus2Div9(x Element) *Element {
	// addition chain:
	//
	//	_10     = 2*1
	//	_11     = 1 + _10
	//	_110    = 2*_11
	//	_111    = 1 + _110
	//	_1101   = _110 + _111
	//	_110100 = _1101 << 2
	//	_110111 = _11 + _110100
	//	_111000 = 1 + _110111
	//	i13     = _111000 << 3 + _111
	//	i22     = i13 << 9
	//	i23     = _110111 + i22
	//	i35     = i22 << 12
	//	i36     = i23 + i35
	//	i48     = i35 << 12
	//	i49     = i36 + i48
	//	i62     = i48 << 12 + i49
	//	i73     = (1 + i62) << 9 + i13
	//	i264    = ((i73 << 66 + i73) << 66 + i73) << 57
	//	return    i62 + i264
	//
	// Operations: 250 squares 15 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: t1 = x^0x6
	t1.Square(z)

	// Step 4: t0 = x^0x7
	t0.Mul(&x, &t1)

	// Step 5: t1 = x^0xd
	t1.Mul(&t1, &t0)

	// Step 7: t1 = x^0x34
	for range 2 {
		t1.Square(&t1)
	}

	// Step 8: z = x^0x37
	z.Mul(z, &t1)

	// Step 9: t1 = x^0x38
	t1.Mul(&x, z)

	// Step 12: t1 = x^0x1c0
	for range 3 {
		t1.Square(&t1)
	}

	// Step 13: t0 = x^0x1c7
	t0.Mul(&t0, &t1)

	// Step 22: t1 = x^0x38e00
	t1.Square(&t0)
	for s := 1; s < 9; s++ {
		t1.Square(&t1)
	}

	// Step 23: z = x^0x38e37
	z.Mul(z, &t1)

	// Step 35: t1 = x^0x38e00000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 36: z = x^0x38e38e37
	z.Mul(z, &t1)

	// Step 48: t1 = x^0x38e00000000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 49: z = x^0x38e38e38e37
	z.Mul(z, &t1)

	// Step 61: t1 = x^0x38e00000000000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 62: z = x^0x38e38e38e38e37
	z.Mul(z, &t1)

	// Step 63: t1 = x^0x38e38e38e38e38
	t1.Mul(&x, z)

	// Step 72: t1 = x^0x71c71c71c71c7000
	for range 9 {
		t1.Square(&t1)
	}

	// Step 73: t0 = x^0x71c71c71c71c71c7
	t0.Mul(&t0, &t1)

	// Step 139: t1 = x^0x1c71c71c71c71c71c0000000000000000
	t1.Square(&t0)
	for s := 1; s < 66; s++ {
		t1.Square(&t1)
	}

	// Step 140: t1 = x^0x1c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(&t0, &t1)

	// Step 206: t1 = x^0x71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for range 66 {
		t1.Square(&t1)
	}

	// Step 207: t0 = x^0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t0.Mul(&t0, &t1)

	// Step 264: t0 = x^0xe38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e00000000000000
	for range 57 {
		t0.Square(&t0)
	}

	// Step 265: z = x^0xe38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e37
	z.Mul(z, &t0)

	return z
}

// ExpByCbrtHelperQMinus7Div9 is equivalent to z.Exp(x, e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e36).
// It raises x to the (q-7)/9 power using an addition chain.
// This helper is used by cbrtAndNormInverse to share exponentiation between
// cube root and norm inverse computations.
//
// uses github.com/mmcloughlin/addchain v0.4.0 to generate a shorter addition chain
func (z *Element) ExpByCbrtHelperQMinus7Div9(x Element) *Element {
	// addition chain:
	//
	//	_10    = 2*1
	//	_11    = 1 + _10
	//	_110   = 2*_11
	//	_111   = 1 + _110
	//	_1101  = _110 + _111
	//	_11010 = 2*_1101
	//	_11011 = 1 + _11010
	//	_11100 = 1 + _11011
	//	i13    = _11100 << 4 + _111
	//	i21    = i13 << 8
	//	i22    = _11011 + i21
	//	i34    = i21 << 12
	//	i35    = i22 + i34
	//	i47    = i34 << 12
	//	i48    = i35 + i47
	//	i61    = i47 << 12 + i48
	//	i73    = (1 + i61) << 10 + i13
	//	i263   = ((i73 << 66 + i73) << 66 + i73) << 56
	//	return   2*(i61 + i263)
	//
	// Operations: 250 squares 15 multiplies
	var t0, t1 Element

	// Step 1: z = x^0x2
	z.Square(&x)

	// Step 2: z = x^0x3
	z.Mul(&x, z)

	// Step 3: z = x^0x6
	z.Square(z)

	// Step 4: t0 = x^0x7
	t0.Mul(&x, z)

	// Step 5: z = x^0xd
	z.Mul(z, &t0)

	// Step 6: z = x^0x1a
	z.Square(z)

	// Step 7: z = x^0x1b
	z.Mul(&x, z)

	// Step 8: t1 = x^0x1c
	t1.Mul(&x, z)

	// Step 12: t1 = x^0x1c0
	for range 4 {
		t1.Square(&t1)
	}

	// Step 13: t0 = x^0x1c7
	t0.Mul(&t0, &t1)

	// Step 21: t1 = x^0x1c700
	t1.Square(&t0)
	for s := 1; s < 8; s++ {
		t1.Square(&t1)
	}

	// Step 22: z = x^0x1c71b
	z.Mul(z, &t1)

	// Step 34: t1 = x^0x1c700000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 35: z = x^0x1c71c71b
	z.Mul(z, &t1)

	// Step 47: t1 = x^0x1c700000000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 48: z = x^0x1c71c71c71b
	z.Mul(z, &t1)

	// Step 60: t1 = x^0x1c700000000000
	for range 12 {
		t1.Square(&t1)
	}

	// Step 61: z = x^0x1c71c71c71c71b
	z.Mul(z, &t1)

	// Step 62: t1 = x^0x1c71c71c71c71c
	t1.Mul(&x, z)

	// Step 72: t1 = x^0x71c71c71c71c7000
	for range 10 {
		t1.Square(&t1)
	}

	// Step 73: t0 = x^0x71c71c71c71c71c7
	t0.Mul(&t0, &t1)

	// Step 139: t1 = x^0x1c71c71c71c71c71c0000000000000000
	t1.Square(&t0)
	for s := 1; s < 66; s++ {
		t1.Square(&t1)
	}

	// Step 140: t1 = x^0x1c71c71c71c71c71c71c71c71c71c71c7
	t1.Mul(&t0, &t1)

	// Step 206: t1 = x^0x71c71c71c71c71c71c71c71c71c71c71c0000000000000000
	for range 66 {
		t1.Square(&t1)
	}

	// Step 207: t0 = x^0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c7
	t0.Mul(&t0, &t1)

	// Step 263: t0 = x^0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c700000000000000
	for range 56 {
		t0.Square(&t0)
	}

	// Step 264: z = x^0x71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71c71b
	z.Mul(z, &t0)

	// Step 265: z = x^0xe38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e36
	z.Square(z)

	return z
}
